import type { Metadata } from "next";
import { arimaFont, interFont } from "./fonts/fontsConfig";
import "./globals.css";
import StateProvider from "./state_management/provider";
import PageContainer from "./Containers/PageContainer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${arimaFont.className} antialiased  bg-white text-gray-700`}
      >
        <StateProvider>
            <PageContainer>
              {children}
            </PageContainer>
        </StateProvider>
      </body>
    </html>
  );
}
